/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LogInRouteImport } from './routes/log-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/_layout'
import { Route as ProtectedLayoutIndexRouteImport } from './routes/_protected/_layout/index'
import { Route as ProtectedLayoutCalendarsRouteImport } from './routes/_protected/_layout/calendars'
import { Route as ProtectedLayoutHomePageRouteImport } from './routes/_protected/_layout/home-page'
import { Route as ProtectedLayoutTeamsRouteImport } from './routes/_protected/_layout/teams'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInRoute = LogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLayoutIndexRoute = ProtectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutCalendarsRoute =
  ProtectedLayoutCalendarsRouteImport.update({
    id: '/calendars',
    path: '/calendars',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutHomePageRoute = ProtectedLayoutHomePageRouteImport.update({
  id: '/home-page',
  path: '/home-page',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutTeamsRoute = ProtectedLayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedLayoutIndexRoute
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/calendars': typeof ProtectedLayoutCalendarsRoute
  '/home-page': typeof ProtectedLayoutHomePageRoute
  '/teams': typeof ProtectedLayoutTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedLayoutIndexRoute
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/calendars': typeof ProtectedLayoutCalendarsRoute
  '/home-page': typeof ProtectedLayoutHomePageRoute
  '/teams': typeof ProtectedLayoutTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/log-in': typeof LogInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/_layout': typeof ProtectedLayoutRouteWithChildren
  '/_protected/_layout/calendars': typeof ProtectedLayoutCalendarsRoute
  '/_protected/_layout/home-page': typeof ProtectedLayoutHomePageRoute
  '/_protected/_layout/teams': typeof ProtectedLayoutTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/_layout/': typeof ProtectedLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/log-in'
    | '/sign-up'
    | '/calendars'
    | '/home-page'
    | '/teams'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/log-in'
    | '/sign-up'
    | '/calendars'
    | '/home-page'
    | '/teams'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_protected'
    | '/log-in'
    | '/sign-up'
    | '/_protected/_layout'
    | '/_protected/_layout/calendars'
    | '/_protected/_layout/home-page'
    | '/_protected/_layout/teams'
    | '/api/auth/$'
    | '/_protected/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LogInRoute: typeof LogInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in': {
      id: '/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof LogInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_layout': {
      id: '/_protected/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_layout/': {
      id: '/_protected/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/calendars': {
      id: '/_protected/_layout/calendars'
      path: '/calendars'
      fullPath: '/calendars'
      preLoaderRoute: typeof ProtectedLayoutCalendarsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/home-page': {
      id: '/_protected/_layout/home-page'
      path: '/home-page'
      fullPath: '/home-page'
      preLoaderRoute: typeof ProtectedLayoutHomePageRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/teams': {
      id: '/_protected/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof ProtectedLayoutTeamsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutCalendarsRoute: typeof ProtectedLayoutCalendarsRoute
  ProtectedLayoutHomePageRoute: typeof ProtectedLayoutHomePageRoute
  ProtectedLayoutTeamsRoute: typeof ProtectedLayoutTeamsRoute
  ProtectedLayoutIndexRoute: typeof ProtectedLayoutIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutCalendarsRoute: ProtectedLayoutCalendarsRoute,
  ProtectedLayoutHomePageRoute: ProtectedLayoutHomePageRoute,
  ProtectedLayoutTeamsRoute: ProtectedLayoutTeamsRoute,
  ProtectedLayoutIndexRoute: ProtectedLayoutIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LogInRoute: LogInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
