/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutCalendarIndexRouteImport } from './routes/_layout/calendar/index'
import { Route as LayoutCalendarCalendarIdRouteImport } from './routes/_layout/calendar/$calendarId'
import { Route as LayoutTeamsIndexRouteImport } from './routes/_layout/teams/index'
import { Route as LayoutTeamsTeamSlugRouteImport } from './routes/_layout/teams/$teamSlug'
import { Route as LayoutTeamsTeamSlugIndexRouteImport } from './routes/_layout/teams/$teamSlug/index'
import { Route as LayoutTeamsTeamSlugPageSlugRouteImport } from './routes/_layout/teams/$teamSlug/$pageSlug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarIndexRoute = LayoutCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalendarCalendarIdRoute =
  LayoutCalendarCalendarIdRouteImport.update({
    id: '/calendar/$calendarId',
    path: '/calendar/$calendarId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTeamsIndexRoute = LayoutTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsTeamSlugRoute = LayoutTeamsTeamSlugRouteImport.update({
  id: '/teams/$teamSlug',
  path: '/teams/$teamSlug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsTeamSlugIndexRoute =
  LayoutTeamsTeamSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutTeamsTeamSlugRoute,
  } as any)
const LayoutTeamsTeamSlugPageSlugRoute =
  LayoutTeamsTeamSlugPageSlugRouteImport.update({
    id: '/$pageSlug',
    path: '/$pageSlug',
    getParentRoute: () => LayoutTeamsTeamSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendar/$calendarId': typeof LayoutCalendarCalendarIdRoute
  '/teams/$teamSlug': typeof LayoutTeamsTeamSlugRouteWithChildren
  '/calendar/': typeof LayoutCalendarIndexRoute
  '/teams/': typeof LayoutTeamsIndexRoute
  '/teams/$teamSlug/$pageSlug': typeof LayoutTeamsTeamSlugPageSlugRoute
  '/teams/$teamSlug/': typeof LayoutTeamsTeamSlugIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/': typeof LayoutIndexRoute
  '/calendar/$calendarId': typeof LayoutCalendarCalendarIdRoute
  '/calendar': typeof LayoutCalendarIndexRoute
  '/teams': typeof LayoutTeamsIndexRoute
  '/teams/$teamSlug/$pageSlug': typeof LayoutTeamsTeamSlugPageSlugRoute
  '/teams/$teamSlug': typeof LayoutTeamsTeamSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/calendar/$calendarId': typeof LayoutCalendarCalendarIdRoute
  '/_layout/teams/$teamSlug': typeof LayoutTeamsTeamSlugRouteWithChildren
  '/_layout/calendar/': typeof LayoutCalendarIndexRoute
  '/_layout/teams/': typeof LayoutTeamsIndexRoute
  '/_layout/teams/$teamSlug/$pageSlug': typeof LayoutTeamsTeamSlugPageSlugRoute
  '/_layout/teams/$teamSlug/': typeof LayoutTeamsTeamSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/calendar/$calendarId'
    | '/teams/$teamSlug'
    | '/calendar/'
    | '/teams/'
    | '/teams/$teamSlug/$pageSlug'
    | '/teams/$teamSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/'
    | '/calendar/$calendarId'
    | '/calendar'
    | '/teams'
    | '/teams/$teamSlug/$pageSlug'
    | '/teams/$teamSlug'
  id:
    | '__root__'
    | '/_layout'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_layout/'
    | '/_layout/calendar/$calendarId'
    | '/_layout/teams/$teamSlug'
    | '/_layout/calendar/'
    | '/_layout/teams/'
    | '/_layout/teams/$teamSlug/$pageSlug'
    | '/_layout/teams/$teamSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar/': {
      id: '/_layout/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof LayoutCalendarIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calendar/$calendarId': {
      id: '/_layout/calendar/$calendarId'
      path: '/calendar/$calendarId'
      fullPath: '/calendar/$calendarId'
      preLoaderRoute: typeof LayoutCalendarCalendarIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams/': {
      id: '/_layout/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof LayoutTeamsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams/$teamSlug': {
      id: '/_layout/teams/$teamSlug'
      path: '/teams/$teamSlug'
      fullPath: '/teams/$teamSlug'
      preLoaderRoute: typeof LayoutTeamsTeamSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams/$teamSlug/': {
      id: '/_layout/teams/$teamSlug/'
      path: '/'
      fullPath: '/teams/$teamSlug/'
      preLoaderRoute: typeof LayoutTeamsTeamSlugIndexRouteImport
      parentRoute: typeof LayoutTeamsTeamSlugRoute
    }
    '/_layout/teams/$teamSlug/$pageSlug': {
      id: '/_layout/teams/$teamSlug/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/teams/$teamSlug/$pageSlug'
      preLoaderRoute: typeof LayoutTeamsTeamSlugPageSlugRouteImport
      parentRoute: typeof LayoutTeamsTeamSlugRoute
    }
  }
}

interface LayoutTeamsTeamSlugRouteChildren {
  LayoutTeamsTeamSlugPageSlugRoute: typeof LayoutTeamsTeamSlugPageSlugRoute
  LayoutTeamsTeamSlugIndexRoute: typeof LayoutTeamsTeamSlugIndexRoute
}

const LayoutTeamsTeamSlugRouteChildren: LayoutTeamsTeamSlugRouteChildren = {
  LayoutTeamsTeamSlugPageSlugRoute: LayoutTeamsTeamSlugPageSlugRoute,
  LayoutTeamsTeamSlugIndexRoute: LayoutTeamsTeamSlugIndexRoute,
}

const LayoutTeamsTeamSlugRouteWithChildren =
  LayoutTeamsTeamSlugRoute._addFileChildren(LayoutTeamsTeamSlugRouteChildren)

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCalendarCalendarIdRoute: typeof LayoutCalendarCalendarIdRoute
  LayoutTeamsTeamSlugRoute: typeof LayoutTeamsTeamSlugRouteWithChildren
  LayoutCalendarIndexRoute: typeof LayoutCalendarIndexRoute
  LayoutTeamsIndexRoute: typeof LayoutTeamsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCalendarCalendarIdRoute: LayoutCalendarCalendarIdRoute,
  LayoutTeamsTeamSlugRoute: LayoutTeamsTeamSlugRouteWithChildren,
  LayoutCalendarIndexRoute: LayoutCalendarIndexRoute,
  LayoutTeamsIndexRoute: LayoutTeamsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
